---
driver:
  name: docker
  provision_command: curl -L http://www.chef.io/chef/install.sh | bash
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: dummy

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4
  - name: centos-7
  - name: debian
#  - name: arch
#    driver:
#      image: base/arch
  - name: unknown
    driver:
      image: ubuntu:12.04
      platform: ubuntu
  - name: dockerfile
    driver:
      username: dockerfile
      password: dockerfile
      dockerfile: dockerfiles/Dockerfile
  - name: pxe
    driver:
      dockerfile: dockerfiles/pxe
  - name: database
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      instance_name: db
      publish_all: true
  - name: linked
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      links: "db:db"

suites:
  - name: default
  - name: concurrency

